---
#- hosts: all
- hosts: all
  tasks:
    - name: exec local script
      script: 01_preuserchk.sh
      delegate_to: 127.0.0.1
      become: false
      run_once: true

    - name: copy hosts.txt to remove host
      copy:
        src: ./hosts.txt 
        dest: /tmp/ 

    - name: exec userchk.sh in each node
      script: 01_userchk.sh

    - name: userchk log file name
      set_fact:
        userchklog: "{{DATE}}"
        #userchklog: "{{ansible_date_time.date}}-{{ansible_date_time.time}}"

    - name: fetch userchk log
      fetch:
        src: /tmp/{{userchklog}}
        #dest: /output/{{IP}}/{{IP}}_userchk_{{DATE}}
        dest: /output/{{IP}}/userchk_{{userchklog}}
        flat: yes

    - name: remove hosts.txt local_ip.txt passwd log userchk log from target
      file:
        path: /tmp/{{item}}
        state: absent
      with_items:
         - hosts.txt
         - "{{userchklog}}"
         - local_ip.txt

    - name: exec 01_postuserchk.sh in local host
      script: 01_postuserchk.sh
      delegate_to: 127.0.0.1
      become: false
      run_once: true
